# Generated by Django 2.2.3 on 2019-07-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'01': 'Ju lutem shkruani një email të vlefshëm.'}, max_length=254, unique=True, verbose_name='E-mail')),
                ('message', models.TextField(blank=True, help_text='Nëse keni diçka më tepër ju lutem shkruajeni këtu.', null=True, verbose_name='Mesazhi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Ora')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mails',
                'db_table': 'email',
            },
        ),
    ]
