# Generated by Django 2.2.3 on 2019-07-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(help_text="Shkruani emailin dhe t'ju kontaktojmë.", max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
